const { test } = require('node:test');
const assert = require('node:assert/strict');
const { mkdtempSync, rmSync } = require('node:fs');
const { tmpdir } = require('node:os');
const { join } = require('node:path');
const { Store } = require('../electron/store.cjs');
const { parseSkill, exportSkill } = require('../electron/extensions.cjs');
test('超过旧保存上限的正文、资料、Skill及备份在重新打开数据库后仍完整',t=>{
 const dir=mkdtempSync(join(tmpdir(),'xm-full-content-'));
 let db=new Store(join(dir,'test.sqlite'));
 t.after(()=>{db.close();rmSync(dir,{recursive:true,force:true});});
 const long='完整开头'+'甲'.repeat(220000)+'完整结尾';
 const book=db.createBook({title:'长篇资料',premise:long});
 assert.equal(book.contextChapters,100);
 db.updateBook(book.id,{outline:long,world:long,style:long,reference:long,characters:[{id:'p',name:'甲',role:'主角',description:long,characterKnown:long,readerKnown:long,authorNotes:long}],worldRecords:[{id:'w',title:'世界',category:'规则',description:long}],memos:[{id:'m',title:'灵感',content:long}]});
 db.updateChapter(book.chapters[0].id,{body:long,outline:long,summary:long},1);
 db.saveVolume(book.id,{title:'第一卷',outline:long,detail:long});
 const skill=db.saveSkill({...parseSkill('---\nname: 长规则\ntasks: [write]\n---\n'+long),enabled:true});
 assert.equal(parseSkill(exportSkill(skill)).body,long);
 assert.throws(()=>db.updateBook(book.id,{outline:123}),/格式/);
 db.close();db=new Store(join(dir,'test.sqlite'));
 const restored=db.book(book.id);
 assert.equal(restored.chapters[0].body,long);assert.equal(restored.style,long);
 assert.equal(restored.characters[0].characterKnown,long);
 assert.equal(restored.volumes[0].detail,long);
 assert.equal(db.skills().find(s=>s.id===skill.id).body,long);
 const backup=db.backup().books.find(b=>b.id===book.id);
 assert.equal(backup.reference,long);assert.equal(backup.memos[0].content,long);
});
